# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: rpm/golang-github-linuxdeepin-go-x11-client.spec

# add or remove files that should be synced
synced_files:
    - rpm/golang-github-linuxdeepin-go-x11-client.spec
    - .packit.yaml

upstream_package_name: go-x11-client
# downstream (Fedora) RPM package name
downstream_package_name: golang-github-linuxdeepin-go-x11-client

actions:
  fix-spec-file: |
    bash -c "sed -i -e \"s/Version:.*/Version: ${PACKIT_PROJECT_VERSION}/\" rpm/golang-github-linuxdeepin-go-x11-client.spec"
